# fly.toml file generated for fastapi-app on 2025-01-08

app = "fast_api"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true

[[services]]
  internal_port = 8000
  protocol = "tcp"
  ports = ["80", "443"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20 

  [services.http_checks]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/"